version: 2

jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Build all targets
          command: cargo build --all --all-targets
  unit-test:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Run all tests
          command: cargo test --all
  end-to-end-test:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: install BATS
          command: |
            if which git > /dev/null; then
              git clone https://github.com/sstephenson/bats.git
            else
              echo "git is required to install BATS"
              exit 1
            fi

            cd bats
            sudo ./install.sh /usr/local || \
              ./install.sh /usr/local
            cd ..
            rm -rf bats
      - run:
          name: config git
          command: |
            git config --global user.email "you@example.com" && \
            git config --global user.name "Your Name"
      - run:
          name: dev build
          command: cargo build
      - run:
          name: Run all tests
          command: ./test/end-to-end/test.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - unit-test
      - end-to-end-test