name: CI
on: [push]

jobs:
  build_and_test:
    name: git-local-prune
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: unit test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: end-to-end test
        uses: actions/bin/bats@master
        with:
          command: ./test/end-to-end/test.sh